// Builds canonical links from a CheckResult back to the matching docs
// detail page on the published agentready docs site. Renderers that
// support hyperlinks (markdown report, HTML extension report) wrap the
// check id in a link; the JSON output carries it as a `docsUrl` field
// for machine consumers. Stdout text output ignores it.
//
// The URL pattern matches the Astro routes generated by
// `packages/apps/docs/src/pages/scorecards/[version]/checks/[id].astro`.
// Astro is configured with `trailingSlash: 'always'`, so the trailing
// slash is preserved here to avoid a redirect on every click.

export const DOCS_BASE_URL = 'https://timothyjordan.github.io/a14y';

export function buildCheckDocsUrl(scorecardVersion: string, checkId: string): string {
  return `${DOCS_BASE_URL}/scorecards/${scorecardVersion}/checks/${checkId}/`;
}
