/**
 * Loaders for `/research/` case study pages. Reads JSON snapshots under
 * `src/data/case-studies/<slug>/case-study.json`, each generated by the
 * `a14y-benchmark publish` command in the private a14y-internal repo.
 * Pages and components import from here so the snapshot shape is
 * decoupled from template code.
 */

const caseStudyModules = import.meta.glob<{ default: CaseStudy }>(
  '../data/case-studies/*/case-study.json',
  { eager: true },
);

const CASE_STUDIES: CaseStudy[] = Object.values(caseStudyModules)
  .map((mod) => mod.default)
  .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));

export interface CaseStudy {
  slug: string;
  title: string;
  shortTitle: string;
  publishedAt: string;
  scorecardVersion: string;
  tldr: string;
  question: string;
  headline: CaseStudyHeadline;
  methodology: CaseStudyMethodology;
  targets: { a14y: CaseStudyTarget; baseline: CaseStudyTarget };
  results: CaseStudyResultsRow[];
  mechanism: CaseStudyMechanism;
  perRun: { a14y: PerRunMetrics[]; baseline: PerRunMetrics[] };
  judgeQuotes: JudgeQuote[];
  finalResponse: {
    a14y: { n: number; score: number | null; text: string };
    baseline: { n: number; score: number | null; text: string };
  };
  implications: ImplicationBlock[];
  caveats: string[];
  reproduce: ReproduceBlock;
}

export interface CaseStudyHeadline {
  tokensFactor: number;
  toolCallsFactor: number;
  wallClockDeltaPct: number;
  scoreA14y: ScoreStats;
  scoreBaseline: ScoreStats;
  passRateA14y: { passed: number; total: number };
  passRateBaseline: { passed: number; total: number };
}

export interface ScoreStats {
  mean: number;
  stddev: number;
  n: number;
}

export interface CaseStudyMethodology {
  specId: string;
  specHash: string;
  prompt: string;
  rubric: { mode: string; judgeModel?: string };
  agent: string;
  image: string;
  imageDigest: string;
  runtime: string;
  authKind: string;
  authVolume?: string;
  reps: number;
  date: string;
  startedAt: string;
  finishedAt: string;
}

export interface CaseStudyTarget {
  label: string;
  shortLabel?: string;
  url: string | null;
  displayUrl: string;
  publishUrl: boolean;
  note?: string;
}

export interface CaseStudyResultsRow {
  label: string;
  a14y: string;
  baseline: string;
  deltaPct: number | null;
  deltaLabel: string;
  emphasis?: 'tokens' | 'tool-calls' | 'wall-clock' | 'judge';
}

export interface CaseStudyMechanism {
  intro: string;
  rows: { file: string; a14y: string; baseline: string }[];
  followup?: string;
}

export interface PerRunMetrics {
  n: number;
  score: number | null;
  passed: boolean;
  durationMs: number;
  tokens: number;
  toolCalls: number;
}

export interface JudgeQuote {
  target: 'a14y' | 'baseline';
  n: number;
  score: number | null;
  reasoning: string;
}

export interface ImplicationBlock {
  audience: string;
  body: string;
}

export interface ReproduceBlock {
  intro: string;
  commands: string[];
  prereqs: string[];
}

export interface CaseStudyMeta {
  slug: string;
  shortTitle: string;
  title: string;
  publishedAt: string;
  scorecardVersion: string;
  tldr: string;
  headlineTokensFactor: number;
}

/**
 * Map a case study slug to its URL path on the docs site. The detail page
 * file name (and thus the URL) doesn't always match the slug because slugs
 * encode a date suffix for traceability; the URL is the shareable
 * marketing surface. Add new mappings here when shipping new case studies.
 */
const SLUG_TO_PATH: Record<string, string> = {
  'agent-readiness-layer-2026-05-16': 'scorecard-evals',
};

export function caseStudyUrl(slug: string, base: string): string {
  const path = SLUG_TO_PATH[slug] ?? slug;
  return `${base}/research/${path}/`;
}

export function listCaseStudies(): CaseStudyMeta[] {
  return CASE_STUDIES.map((cs) => ({
    slug: cs.slug,
    shortTitle: cs.shortTitle,
    title: cs.title,
    publishedAt: cs.publishedAt,
    scorecardVersion: cs.scorecardVersion,
    tldr: cs.tldr,
    headlineTokensFactor: cs.headline.tokensFactor,
  }));
}

export function getCaseStudy(slug: string): CaseStudy {
  const found = CASE_STUDIES.find((cs) => cs.slug === slug);
  if (!found) {
    throw new Error(
      `Case study "${slug}" not found. Available: ${CASE_STUDIES.map((c) => c.slug).join(', ')}`,
    );
  }
  return found;
}
