/**
 * Loaders for the /research/ leaderboard. Reads
 * `src/data/research.json`, which is generated by the @a14y/research
 * package in the private a14y-internal repo and copied in by its
 * `publish` command. Pages and components import from here so the
 * shape of research.json is decoupled from template code.
 */
import researchData from '~/data/research.json';

export type SiteCategory =
  | 'docs-platform'
  | 'consumer'
  | 'dev-tool'
  | 'enterprise'
  | 'reference';

export type RunMode = 'page' | 'site';

export interface LeaderboardEntry {
  slug: string;
  name: string;
  url: string;
  category: SiteCategory;
  mode: RunMode;
  score: number;
  summary: {
    passed: number;
    failed: number;
    warned: number;
    errored: number;
    na: number;
    total: number;
    applicable: number;
  };
  topFailures: string[];
  scannedAt: string;
}

export interface CategoryStat {
  category: SiteCategory;
  n: number;
  meanScore: number;
  medianScore: number;
}

export interface ScoreHistogramBucket {
  from: number;
  to: number;
  label: string;
  n: number;
}

export interface CheckPassRate {
  checkId: string;
  name: string;
  group?: string;
  scope: 'site' | 'page';
  applicableSites: number;
  passingSites: number;
  passRate: number;
}

export interface ResearchData {
  scorecardVersion: string;
  scorecardReleasedAt: string;
  generatedAt: string;
  sites: LeaderboardEntry[];
  stats: {
    byCategory: CategoryStat[];
    scoreHistogram: ScoreHistogramBucket[];
    checkPassRates: CheckPassRate[];
  };
}

const data = researchData as ResearchData;

export function getResearchData(): ResearchData {
  return data;
}

export function getLeaderboard(): LeaderboardEntry[] {
  return data.sites;
}

export function getCategoryStats(): CategoryStat[] {
  return data.stats.byCategory;
}

export function getScoreHistogram(): ScoreHistogramBucket[] {
  return data.stats.scoreHistogram;
}

/**
 * Returns the N hardest checks (lowest pass rate) where at least
 * `minApplicable` sites had the check applicable. The threshold filters
 * out checks that only one or two sites trigger, which would otherwise
 * dominate the bottom of the list.
 */
export function getHardestChecks(n = 12, minApplicable = 5): CheckPassRate[] {
  return data.stats.checkPassRates
    .filter((c) => c.applicableSites >= minApplicable)
    .slice(0, n);
}

export const CATEGORY_LABELS: Record<SiteCategory, string> = {
  'docs-platform': 'Docs platform',
  'dev-tool': 'Dev tool',
  enterprise: 'Enterprise SaaS',
  reference: 'Reference',
  consumer: 'Consumer',
};

/**
 * Bucket name used for color coding scores in the leaderboard.
 *  excellent ≥85, good ≥70, fair ≥50, poor <50.
 */
export function scoreBand(score: number): 'excellent' | 'good' | 'fair' | 'poor' {
  if (score >= 85) return 'excellent';
  if (score >= 70) return 'good';
  if (score >= 50) return 'fair';
  return 'poor';
}
