/**
 * Loaders for the /research/ leaderboard. Reads
 * `src/data/research.json`, which is generated by the @a14y/research
 * package in the private a14y-internal repo and copied in by its
 * `publish` command. Pages and components import from here so the
 * shape of research.json is decoupled from template code.
 */
import researchData from '~/data/research.json';

export type SiteCategory =
  | 'docs-platform'
  | 'consumer'
  | 'dev-tool'
  | 'enterprise'
  | 'reference';

export type RunMode = 'page' | 'site';

export interface LeaderboardEntry {
  slug: string;
  name: string;
  url: string;
  category: SiteCategory;
  mode: RunMode;
  score: number;
  summary: {
    passed: number;
    failed: number;
    warned: number;
    errored: number;
    na: number;
    total: number;
    applicable: number;
  };
  topFailures: string[];
  scannedAt: string;
}

export interface CategoryStat {
  category: SiteCategory;
  n: number;
  meanScore: number;
  medianScore: number;
}

export interface ScoreHistogramBucket {
  from: number;
  to: number;
  label: string;
  n: number;
}

export interface CheckPassRate {
  checkId: string;
  name: string;
  group?: string;
  scope: 'site' | 'page';
  applicableSites: number;
  passingSites: number;
  passRate: number;
}

export interface ResearchData {
  scorecardVersion: string;
  scorecardReleasedAt: string;
  generatedAt: string;
  sites: LeaderboardEntry[];
  stats: {
    byCategory: CategoryStat[];
    scoreHistogram: ScoreHistogramBucket[];
    checkPassRates: CheckPassRate[];
  };
}

const data = researchData as ResearchData;

export function getResearchData(): ResearchData {
  return data;
}

export function getLeaderboard(): LeaderboardEntry[] {
  return data.sites;
}

export function getCategoryStats(): CategoryStat[] {
  return data.stats.byCategory;
}

export function getScoreHistogram(): ScoreHistogramBucket[] {
  return data.stats.scoreHistogram;
}

/**
 * Returns the N hardest checks (lowest pass rate) where at least
 * `minApplicable` sites had the check applicable. The threshold filters
 * out checks that only one or two sites trigger, which would otherwise
 * dominate the bottom of the list.
 */
export function getHardestChecks(n = 12, minApplicable = 5): CheckPassRate[] {
  return data.stats.checkPassRates
    .filter((c) => c.applicableSites >= minApplicable)
    .slice(0, n);
}

export const CATEGORY_LABELS: Record<SiteCategory, string> = {
  'docs-platform': 'Docs platform',
  'dev-tool': 'Dev tool',
  enterprise: 'Enterprise SaaS',
  reference: 'Reference',
  consumer: 'Consumer',
};

/**
 * Bucket name used for color coding scores in the leaderboard.
 *  excellent ≥85, good ≥70, fair ≥50, poor <50.
 */
export function scoreBand(score: number): 'excellent' | 'good' | 'fair' | 'poor' {
  if (score >= 85) return 'excellent';
  if (score >= 70) return 'good';
  if (score >= 50) return 'fair';
  return 'poor';
}

/**
 * Build the docs URL for a scorecard check, e.g. "html.glossary-link" →
 * "/scorecards/0.2.0/checks/html.glossary-link/". Honors the site's
 * BASE_URL so it works correctly when deployed under a non-root path.
 */
export function checkDocsUrl(scorecardVersion: string, checkId: string): string {
  const base = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '');
  return `${base}/scorecards/${scorecardVersion}/checks/${checkId}/`;
}

/** Share of catalog sites where every site-level llms.txt check passed. */
export function getLlmsTxtAdoption(): { passing: number; total: number; pct: number } {
  const llmsExists = data.stats.checkPassRates.find((c) => c.checkId === 'llms-txt.exists');
  if (!llmsExists) return { passing: 0, total: 0, pct: 0 };
  const pct =
    llmsExists.applicableSites === 0
      ? 0
      : Math.round((llmsExists.passingSites / llmsExists.applicableSites) * 100);
  return {
    passing: llmsExists.passingSites,
    total: llmsExists.applicableSites,
    pct,
  };
}

/** The check id that appears most often in any site's topFailures list across the catalog. */
export function getMostCommonTopFailure(): { checkId: string; siteCount: number } | null {
  const counts = new Map<string, number>();
  for (const site of data.sites) {
    for (const id of site.topFailures) {
      counts.set(id, (counts.get(id) ?? 0) + 1);
    }
  }
  let best: { checkId: string; siteCount: number } | null = null;
  for (const [checkId, n] of counts) {
    if (!best || n > best.siteCount) best = { checkId, siteCount: n };
  }
  return best;
}
